### ISSUE TITLE
php artisan key:generate 有点问题了？

### ISSUE THREAD

**Issue by jeizas** [stoneworld/NeteaseCloudMusic#3]
![image](https://user-images.githubusercontent.com/12405225/38171634-26bc4f4c-35d0-11e8-94ec-f44dfc9aa882.png)

没用过php，这个错误怎么办呢？

**Comment by stoneworld** [comment]
fixed

**Comment by jeizas** [comment]
后来安装成功插件之后可以运行了，但是抓取到的评论好像很少？

**Comment by stoneworld** [comment]
这我就不清楚了
